# Generated by Django 5.0.6 on 2024-09-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_store_comment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mypage.store'),
        ),
    ]
