# Generated by Django 5.0.6 on 2024-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_alter_comment_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(null=True, upload_to='stores/'),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
